export const studentPaymentConfirmedEmailTemplate = String.raw`<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="x-apple-disable-message-reformatting">
  <meta name="color-scheme" content="light">
  <meta name="supported-color-schemes" content="light">
  <title>Pagamento confirmado - MAZZI</title>
  <style>
    @media only screen and (max-width: 620px) {
      .outer-padding{padding:12px 8px!important}.email-shell{width:100%!important;border-radius:12px!important}.hero-padding{padding:24px 20px!important}.content-padding{padding-left:20px!important;padding-right:20px!important}.hero-title{font-size:27px!important;line-height:32px!important}.detail-cell{display:block!important;width:100%!important;padding:0 0 16px 0!important}.detail-cell-last{padding-bottom:0!important}.mobile-center{text-align:center!important}
    }
  </style>
</head>
<body data-mazzi-template="student-payment-confirmed-email-first-v3" style="margin:0;padding:0;background-color:#eef0f2;color:#24262d;font-family:Arial,Helvetica,sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;visibility:hidden;">Pagamento aprovado. Sua aula está confirmada no MAZZI.</div>
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background-color:#eef0f2;border-collapse:collapse;border-spacing:0;"><tr><td class="outer-padding" align="center" style="padding:28px 16px;">
    <table role="presentation" width="600" class="email-shell" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:600px;background-color:#fff;border-radius:16px;overflow:hidden;border-collapse:separate;border-spacing:0;">
      <tr><td class="hero-padding" style="padding:24px 32px;background-color:#0d0f12;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;border-spacing:0;"><tr>
        <td valign="middle" align="center"><div style="color:#f6c945;font-size:21px;line-height:25px;font-weight:800;letter-spacing:-.4px;">MAZZI</div><div style="margin-top:3px;color:#f2f4f6;font-size:12px;line-height:17px;font-weight:600;opacity:.72;">Sua jornada, no seu ritmo.</div></td>
      </tr></table></td></tr>
      <tr><td class="hero-padding mobile-center" align="center" style="padding:30px 48px 28px;background-color:#0d0f12;"><div style="display:inline-block;padding:7px 12px;background-color:#ffffff;border-radius:999px;color:#202126;font-size:11px;line-height:14px;font-weight:700;letter-spacing:.3px;">Pagamento aprovado</div><h1 class="hero-title" style="margin:16px 0 0;color:#ffffff;font-size:32px;line-height:38px;font-weight:800;letter-spacing:-.8px;">Sua aula está confirmada</h1><p style="margin:12px 0 0;color:#d4d7dc;font-size:16px;line-height:24px;font-weight:400;">Olá, {{student_name}}! Seu pagamento foi aprovado e o profissional já foi notificado.</p><div style="margin-top:18px;color:#b8bbc2;font-size:12px;line-height:18px;">Identificação do pagamento</div><div style="margin-top:3px;color:#ffffff;font-size:13px;line-height:19px;font-weight:700;overflow-wrap:anywhere;">{{payment_reference}}</div></td></tr>
      <tr><td class="content-padding" style="padding:28px 32px 0;background-color:#fff;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="border-radius:12px;border-collapse:separate;border-spacing:0;"><tr><td style="padding:20px 20px 18px;"><div style="color:#777d86;font-size:10px;line-height:14px;font-weight:800;letter-spacing:1.1px;text-transform:uppercase;">Sua aula</div><div style="margin-top:6px;color:#202126;font-size:20px;line-height:25px;font-weight:800;">{{provider_name}}</div>
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:18px;border-collapse:collapse;border-spacing:0;"><tr><td class="detail-cell" width="50%" valign="top" style="width:50%;padding:0 12px 0 0;"><div style="color:#777d86;font-size:12px;line-height:18px;">Data</div><div style="margin-top:3px;color:#202126;font-size:14px;line-height:20px;font-weight:700;">{{lesson_date}}</div></td><td class="detail-cell detail-cell-last" width="50%" valign="top" style="width:50%;padding:0 0 0 12px;"><div style="color:#777d86;font-size:12px;line-height:18px;">Horário</div><div style="margin-top:3px;color:#202126;font-size:14px;line-height:20px;font-weight:700;">{{lesson_start_time}} às {{lesson_end_time}}</div></td></tr></table>
        <div style="height:1px;line-height:1px;background-color:#edf0f2;margin:18px 0;"></div>
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;border-spacing:0;"><tr><td class="detail-cell" width="50%" valign="top" style="width:50%;padding:0 12px 0 0;"><div style="color:#777d86;font-size:12px;line-height:18px;">Categoria</div><div style="margin-top:3px;color:#202126;font-size:14px;line-height:20px;font-weight:700;">Categoria {{license_category}}</div></td><td class="detail-cell detail-cell-last" width="50%" valign="top" style="width:50%;padding:0 0 0 12px;"><div style="color:#777d86;font-size:12px;line-height:18px;">Veículo</div><div style="margin-top:3px;color:#202126;font-size:14px;line-height:20px;font-weight:700;">{{vehicle_brand}} {{vehicle_model}}</div><div style="margin-top:2px;color:#777d86;font-size:12px;line-height:18px;">{{vehicle_year}} · {{vehicle_transmission}} · {{vehicle_color}}</div></td></tr></table>
      </td></tr></table></td></tr>
      <tr><td class="content-padding" style="padding:20px 32px 0;background-color:#fff;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color:#f7f8f9;border-radius:12px;border-collapse:separate;border-spacing:0;"><tr><td style="padding:20px;"><div style="color:#777d86;font-size:10px;line-height:14px;font-weight:800;letter-spacing:1.1px;text-transform:uppercase;">Resumo do pagamento</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:12px;border-collapse:collapse;border-spacing:0;"><tr><td style="padding:7px 0;color:#777d86;font-size:13px;line-height:19px;">Valor da aula</td><td align="right" style="padding:7px 0;color:#202126;font-size:13px;line-height:19px;font-weight:600;">{{lesson_amount}}</td></tr><tr><td style="padding:11px 0 0;border-top:1px solid #e2e5e8;color:#202126;font-size:15px;line-height:21px;font-weight:800;">Total pago</td><td align="right" style="padding:11px 0 0;border-top:1px solid #e2e5e8;color:#202126;font-size:18px;line-height:22px;font-weight:800;">{{total_paid}}</td></tr></table></td></tr></table></td></tr>
      <tr><td class="content-padding mobile-center" align="center" style="padding:24px 32px 28px;background-color:#fff;"><a href="{{lesson_url}}" style="display:inline-block;padding:14px 24px;background-color:#202126;border-radius:10px;color:#fff;text-decoration:none;font-size:14px;line-height:18px;font-weight:800;">Ver detalhes da aula</a><p style="margin:14px 0 0;color:#777d86;font-size:12px;line-height:18px;">Você também pode acompanhar tudo pelo aplicativo MAZZI Aluno.</p></td></tr>
      <tr><td align="center" style="padding:20px 28px;background-color:#202126;"><div style="color:#fff;font-size:15px;line-height:20px;font-weight:800;">MAZZI</div><p style="margin:7px 0 0;color:#b8bbc2;font-size:11px;line-height:17px;">E-mail automático de confirmação de pagamento.</p><p style="margin:5px 0 0;color:#858a94;font-size:10px;line-height:15px;">Nunca solicitaremos sua senha ou código de acesso por e-mail.</p></td></tr>
    </table>
  </td></tr></table>
</body>
</html>`;
