import { ButtonBase } from '../ui/Button';
import React from 'react';
import { ChevronRight } from 'lucide-react';

export const PremiumAppHeader: React.FC<{ eyebrow?: string; title: string; subtitle?: string; avatar?: React.ReactNode; action?: React.ReactNode }> = ({ eyebrow, title, subtitle, avatar, action }) => <header className="mb-8 flex items-start justify-between gap-4"><div className="min-w-0">{eyebrow && <p className="mazzi-eyebrow mb-3">{eyebrow}</p>}<h1 className="mazzi-title">{title}</h1>{subtitle && <p className="mt-2 text-sm font-medium text-[var(--mazzi-muted)]">{subtitle}</p>}</div><div className="flex shrink-0 items-center gap-2">{action}{avatar}</div></header>;

export const HeroMetricCard: React.FC<{ primaryValue: React.ReactNode; primaryLabel: string; secondaryValue: React.ReactNode; secondaryLabel: string }> = ({ primaryValue, primaryLabel, secondaryValue, secondaryLabel }) => <section className="mazzi-hero"><div className="p-5"><p className="text-[34px] font-extrabold leading-none tracking-[-.05em]">{primaryValue}</p><p className="mt-2 text-xs font-bold opacity-70">{primaryLabel}</p></div><div className="p-5"><p className="text-[30px] font-extrabold leading-none tracking-[-.04em]">{secondaryValue}</p><p className="mt-2 text-xs font-bold text-white/60">{secondaryLabel}</p></div></section>;

export const MetricTile: React.FC<{ value: React.ReactNode; label: string; icon?: React.ReactNode }> = ({ value, label, icon }) => <div className="mazzi-card p-4"><div className="flex items-center justify-between"><p className="text-2xl font-extrabold tracking-[-.04em]">{value}</p><span className="text-[var(--mazzi-yellow)]">{icon}</span></div><p className="mt-1 text-xs font-semibold text-[var(--mazzi-muted)]">{label}</p></div>;

export const SectionTitle: React.FC<{ children: React.ReactNode; action?: React.ReactNode }> = ({ children, action }) => <div className="mb-4 flex items-center justify-between gap-4"><h2 className="mazzi-section-title">{children}</h2>{action}</div>;

export const PremiumListItem: React.FC<{ icon: React.ReactNode; label: string; value?: React.ReactNode; onClick?: () => void }> = ({ icon, label, value, onClick }) => <ButtonBase type="button" onClick={onClick} className="flex min-h-14 w-full items-center gap-3 px-1 text-left"><span className="grid h-10 w-10 place-items-center rounded-[14px] bg-[var(--mazzi-surface-soft)] text-[var(--mazzi-dark)]">{icon}</span><span className="flex-1 text-sm font-bold">{label}</span>{value && <span className="text-xs font-semibold text-[var(--mazzi-muted)]">{value}</span>}<ChevronRight className="h-4 w-4 text-[var(--mazzi-muted)]"/></ButtonBase>;
